majorproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="base.html"), name="base"),
    path('account/', include('allauth.urls')),
    path('registration/', include('registration.urls')),
    path('task/', include('task.urls')),
    path('project/', include('project.urls')),
    path('task/', include('task.urls')),
    path('charts_and_reports/', include('charts_and_reports.urls')),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from .views import ProjectView, AssignleaderView, AllocateemployeeView, AllocateemployeebyleadView, ProjectList, ProjectUpdateView, ProjectDeleteView, Projectforlead, ProjectdetailView, LeadListView, LeadUpdateView, LeadDeleteView, AllocationListView, AllocationDeleteView, AllocationUpdateView, AllocationListforleadView, AllocationDeleteforleadView, AllocationUpdateforleadView, Projectforemployee, ProjecthealthView, SearchView, SortView, SearchResultView
from project import views

urlpatterns = [
    path('projectlist/', ProjectList.as_view(), name="projectlist"),
    path('projectlistforlead/', Projectforlead.as_view(), name="projectlistforlead"),
    path('projectlistforemployee/', Projectforemployee.as_view(), name="projectlistforemployee"),
    path('createproject/', ProjectView.as_view(), name='createproject'),
    path('projectdetail/<int:id>', ProjectdetailView.as_view(), name="projectdetail"),
    path('projectupdate/<int:id>', ProjectUpdateView.as_view(), name="projectupdate"),
    path('projectdelete/<int:pk>', ProjectDeleteView.as_view(), name="projectdelete"),
    path('assignleader/', AssignleaderView.as_view(), name='assignleader'),
    path('allocateemployee/', AllocateemployeeView.as_view(), name='allocateemployee'),
    path('allocateemployeebylead/', AllocateemployeebyleadView.as_view(), name='allocateemployeebylead'),
    path('teamlead/', LeadListView.as_view(), name='leadlist'),
    path('leadupdate/<int:id>', LeadUpdateView.as_view(), name="leadupdate"),
    path('leaddelete/<int:pk>', LeadDeleteView.as_view(), name="leaddelete"),
    path('allocationlist/', AllocationListView.as_view(), name='allocationlist'),
    path('allocationupdate/<int:id>', AllocationUpdateView.as_view(), name="allocationupdate"),
    path('allocationdelete/<int:pk>/<int:id>', AllocationDeleteView.as_view(), name="allocationdelete"),
    path('allocationlistforlead/', AllocationListforleadView.as_view(), name='allocationlistforlead'),
    path('allocationupdateforlead/<int:id>', AllocationUpdateforleadView.as_view(), name="allocationupdateforlead"),
    path('allocationdeleteforlead/<int:pk>/<int:id>', AllocationDeleteforleadView.as_view(), name="allocationdeleteforlead"),
    path('projecthealth/', ProjecthealthView.as_view(), name='projecthealth'),
    path('search/', SearchView.as_view(), name='search'),
    path('searchresult/', SearchResultView.as_view(), name='searchresult'),
    path('sort/', SortView.as_view(), name='sort'),
]

task/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from task import views
from .views import TaskView, TaskbyleadView, SubtaskView, SubtaskbyleadView, AllocateemployeeView, AllocateemployeebyleadView, validate_task, SubtaskbydeveloperView, TaskList, TaskUpdateView, TaskDeleteView, TaskforleadList, TaskbyuserView, TaskdetailView, TaskSearchView, SearchforleadView, SearchforemployeeView, SortView, SortViewforlead

urlpatterns = [
    path('tasklist/', TaskList.as_view(), name="tasklist"),
    path('tasklistforlead/', TaskforleadList.as_view(), name="tasklistforlead"),
    path('createtask/', TaskView.as_view(), name='createtask'),
    path('taskbylead/', TaskbyleadView.as_view(), name='taskbylead'),
    path('taskbyuser/', TaskbyuserView.as_view(), name='tasklistforusers'),
    path('createsubtask/', SubtaskView.as_view(), name='createsubtask'),
    path('subtaskbylead/', SubtaskbyleadView.as_view(), name='subtaskbylead'),
    path('subtaskbydeveloper/', SubtaskbydeveloperView.as_view(), name='subtaskbydeveloper'),
    path('allocation/', AllocateemployeeView.as_view(), name='allocateemployee_task'),
    path('allocationbylead/', AllocateemployeebyleadView.as_view(), name='allocateemployee_task_lead'),
    path('ajaxjson/', views.validate_task, name='validate_task'),
    path('taskupdate/<int:id>', TaskUpdateView.as_view(), name="taskupdate"),
    path('taskdelete/<int:pk>', TaskDeleteView.as_view(), name="taskdelete"),
    path('taskdetail/<int:id>', TaskdetailView.as_view(), name="taskdetail"),
    path('search/', TaskSearchView.as_view(), name='tasksearch'),
    path('leadsearch/', SearchforleadView.as_view(), name='leadtasksearch'),
    path('employeesearch/', SearchforemployeeView.as_view(), name='employeetasksearch'),
    path('tasksort/', SortView.as_view(), name='tasksort'),
    path('tasksortlead/', SortViewforlead.as_view(), name='tasksortforlead'),
]

project/models.py
from django.db import models
from registration.models import User


class Project(models.Model):
    STATUS_CHOICES = [
        ('underprogress', 'Under progress'),
        ('created', 'Created'),
        ('closed', 'Closed'),
    ]
    name = models.CharField(blank=False, max_length=20, unique=True)
    description = models.TextField(blank=False, max_length=200)
    start_date = models.DateField(blank=False)
    end_date = models.DateField(blank=False)
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default='created')

    def __str__(self):
        return self.name
    @staticmethod
    def project_query():
        context = {'allprojects': Project.objects.all()}
        return context


class Teamlead(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.project.name


class ProjectAllocation(models.Model):
    ROLE_CHOICES = [
        ('Developer', 'Developer'),
        ('UI Designer', 'UI Designer'),
        ('QA', 'QA'),
    ]
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=201, choices=ROLE_CHOICES)
    allocation = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return self.get_role_display()



    # def clean_email(self):
    #     allocation = self.cleaned_data['allocation']
    #
    #     if email.endswith('@cowhite.com'):
    #         raise ValidationError('Domain of email is not valid')
    #
    #     return email

project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.db import transaction
from .models import Project, ProjectAllocation, Teamlead
from registration.models import User
from .forms import Projectform, Assignleaderform, Allocateemployeeform, Allocateemployeebyleadform, Allocateemployeesssform
from django.views.generic import View, ListView, UpdateView, DeleteView
from task.models import Task
from .services import projectview_query, percentageudate_query
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from datetime import datetime
import json
from django.http import JsonResponse
from django.core import serializers

project_list = Project.objects.all().order_by('id')


class ProjectList(View):

    @transaction.atomic
    def get(self, request):
        project_list_list = Project.objects.all()
        page = request.GET.get('page', 1)

        paginator = Paginator(project_list_list, 2)
        try:
            project_list = paginator.page(page)
        except PageNotAnInteger:
            project_list = paginator.page(1)
        except EmptyPage:
            project_list = paginator.page(paginator.num_pages)
        return render(request, 'project/projectlist.html', {'project_list': project_list, 'project_list_list': project_list_list,
                                                            "allproject": Project.objects.filter(teamlead__in=self.request.user.teamlead_set.all())})

class SearchView(View):

    def get(self, request):
        q = request.GET.get('q', None)
        project_list_list = Project.objects.filter(Q(name__icontains=q) | Q(status__icontains=q))
        if project_list_list:
            page = request.GET.get('page', 1)
            paginator = Paginator(project_list_list, 2)
            try:
                project_list = paginator.page(page)
            except PageNotAnInteger:
                project_list = paginator.page(1)
            except EmptyPage:
                project_list = paginator.page(paginator.num_pages)
            return render(request, 'project/projectlist.html', {'project_list': project_list, 'q': q})
        else:
            error = "No such data found."
            project_list_list = Project.objects.all()
            page = request.GET.get('page', 1)

            paginator = Paginator(project_list_list, 2)
            try:
                project_list = paginator.page(page)
            except PageNotAnInteger:
                project_list = paginator.page(1)
            except EmptyPage:
                project_list = paginator.page(paginator.num_pages)
            return render(request, 'project/projectlist.html', {'project_list': project_list, 'error': error})


class Projectforlead(View):

    @transaction.atomic
    def get(self, request):
        return render(request, 'project/projectlist.html', {'project_list': project_list,
                                                            "allproject": Project.objects.filter(teamlead__in=self.request.user.teamlead_set.all())})


class Projectforemployee(View):

    @transaction.atomic
    def get(self, request):
        return render(request, 'project/projectlist.html', {'project_list': project_list,
                                                            "allproject": Project.objects.filter(projectallocation__in=self.request.user.projectallocation_set.all())})


class ProjectUpdateView(UpdateView):
    template_name = 'project/projectupdate.html'
    model = Project
    success_url = reverse_lazy('projectlist')
    fields = ['name', 'description', 'status', 'start_date', 'end_date']
    context_object_name = 'form'

    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Project, id=id)

    def form_valid(self, form):
        super().form_valid(form)
        form.save()
        return redirect("projectlist")


class ProjectDeleteView(DeleteView):
    model = Project
    context_object_name = 'form'
    success_url = reverse_lazy('projectlist')
    template_name = 'project/projectdelete.html'


class ProjectdetailView(View):

    @transaction.atomic
    def get(self, request, id):
        return render(request, 'project/project_detail.html', {'project': Project.objects.get(id=int(id)),
                                                               'dev': ProjectAllocation.objects.filter(project_id=int(id), role=1),
                                                               'lead': Teamlead.objects.filter(project_id=int(id)),
                                                               'error': 'error',
                                                               'qa': ProjectAllocation.objects.filter(project_id=int(id), role=3),
                                                               'ui': ProjectAllocation.objects.filter(project_id=int(id), role=2)})


class ProjectView(View):

    @transaction.atomic
    def get(self, request):
        form = Projectform
        return render(request, 'project/create.html', {'form': form,
                                                       'employee': User.objects.all(),
                                                       'error': 'error'})

    @transaction.atomic
    def post(self, request, **kwargs):
        form = Projectform(request.POST)
        errors = "Make sure you entered dates correctly."
        if request.POST.get('start_date') and request.POST.get('end_date') and request.POST.get(
                'start_date') < request.POST.get('end_date'):
            if Project.objects.filter(name=request.POST.get('name')).count() > 0:
                return render(request, 'project/create.html', {'form': form,
                                                               'error': 'error',
                                                               'employee': User.objects.all()})
            else:
                try:
                    project = Project.objects.latest('id')
                    project = project.id + 1
                except Exception as e:
                    project = 1
                if request.POST.get('lead'):
                    projectview_query(project, request.POST.get('lead'), request.POST.get('name'), request.POST.get('description'), request.POST.get('start_date'), request.POST.get('end_date'), request.POST.get('status'))
                form = Allocateemployeesssform
                return render(request, 'project/create.html', {'form': form,
                                                               'project': project})
        else:
            return render(request, 'project/create.html', {'form': form,
                                                           'errors': errors,
                                                           'employee': User.objects.all()})


class AssignleaderView(View):

    @transaction.atomic
    def get(self, request):
        form = Assignleaderform
        return render(request, 'project/assignleader.html', {'form': form, 'error': 'error'})

    @transaction.atomic
    def post(self, request, **kwargs):
        x = User.objects.get(id=int(request.POST.get('user')))
        x.is_staff = True
        x.save()
        if Teamlead.objects.filter(project_id=int(request.POST.get('project')), user_id=int(request.POST.get('user'))).count() == 0:
            Teamlead.objects.create(project_id=int(request.POST.get('project')), user_id=int(request.POST.get('user')))
            return redirect('userdashboard')
        else:
            form = Assignleaderform
            errors = "Employee already Team Lead in this Project."
            return render(request, 'project/assignleader.html', {'form': form, 'error': 'error', 'errors': errors})


class LeadListView(ListView):

    model = Teamlead
    template_name = "project/leadlist.html"

    def get_queryset(self):
        return Teamlead.objects.all().order_by('project_id')


class LeadUpdateView(UpdateView):
    template_name = 'project/leadupdate.html'
    model = Teamlead
    success_url = reverse_lazy('leadlist')
    fields = ['project', 'user']
    context_object_name = 'form'

    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Teamlead, id=id)

    def form_valid(self, form):
        super().form_valid(form)
        form.save()
        return redirect("leadlist")


class LeadDeleteView(DeleteView):
    model = Teamlead
    context_object_name = 'form'
    success_url = reverse_lazy('leadlist')
    template_name = 'project/leaddelete.html'


class AllocateemployeeView(View):

    @transaction.atomic
    def get(self, request):
        form = Allocateemployeeform
        return render(request, 'project/allocateemployee.html', {'form': form})

    @transaction.atomic
    def post(self, request, **kwargs):
        form = Allocateemployeeform(request.POST)
        user = User.objects.get(id=int(request.POST.get('user')))
        percent = str(100 - user.percentage)
        errors = "Please assign other employee or make percentage value less than or equal to " + percent + '.'
        if request.POST.get('project') and request.POST.get('percentage'):
            updated_value = user.percentage + int(request.POST.get('percentage'))
            if updated_value < 101:
                User.objects.filter(id=int(request.POST.get('user'))).update(percentage=updated_value)
                ProjectAllocation.objects.create(project_id=int(request.POST.get('project')), user_id=int(request.POST.get('user')), role=request.POST.get('role'), allocation=int(request.POST.get('percentage')))
                return redirect('projectlist')
        elif form.is_valid() and request.POST.get('percentage'):
            updated_value = user.percentage + int(request.POST.get('percentage'))
            if updated_value < 101:
                User.objects.filter(id=int(request.POST.get('user'))).update(percentage=updated_value)

templates/project/allocateemployeebylead.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="row-fluid">
    <div class="span6">
      <div class="widget-box">
        <div class="widget-title">
          <h5>Resource Allocation for Project</h5>
        </div>
        <div class="widget-content nopadding">
          <form action="{% url 'allocateemployeebylead' %}" method="post" class="form-horizontal">
           {% csrf_token %}
            <div class="control-group">
                <label class="control-label">Please select Project:</label>
                <div class="controls">
                    <select name="project">
                        {% for nameofproject in project %}
                        <option value="{{ nameofproject.id }}" selected>{{ nameofproject }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
              {% for field in form %}
            <div class="control-group">
              <label class="control-label">{{ field.label_tag }}</label>
              <div class="controls">
                {{ field }}
                {{ field.errors }}
              </div>
            </div>
              {% endfor %}
            <div class="control-group">
              <label class="control-label">Allocation in Percentage:</label>
                <div class="controls">
                  <input type="number" pattern="[0-9]{1}{2}{3}" name="percentage">
              </div>
            </div>
              {{ errors }}
              <div class="form-actions">
              <button type="submit" class="btn btn-success">Allocate</button>
              </div>
              {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
              {% endif %}<br>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/project/allocationdelete.html
{% extends "index.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="row-fluid">
    <div class="span6">
      <div class="widget-box">
        <div class="widget-title">
          <h5>Remove Employee from project</h5>
        </div>
        <div class="widget-content nopadding">
          <form method="post" class="form-horizontal">
           {% csrf_token %}
              <input type="hidden" name="data-id" value="{{ object.user.id }}">
                  <input type="hidden" name="data-allocation" value="{{ object.user.allocation }}">
                    <div class="control-group">
                        <label class="control-label"></label>
                        <div class="controls">
                            Are you sure you want to remove project named: <strong>{{ employee.username }}</strong>?
                        </div>
                    </div>
              <div class="form-actions">
              <button type="submit" value="Confirm" class="btn btn-danger" id="delete">Yes</button>
              <button type="button" value="Cancel" class="btn btn-light"><a href="{% url 'allocationlist' %}">No</a></button>
              </div>
              {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
              {% endif %}<br>
          </form>
        </div>
      </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'js/deleteallocation.js' %}"></script>
{% endblock %}

templates/project/allocationdeleteforlead.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="row-fluid">
    <div class="span6">
      <div class="widget-box">
        <div class="widget-title">
          <h5>Remove Employee from project</h5>
        </div>
        <div class="widget-content nopadding">
          <form method="post" class="form-horizontal">
           {% csrf_token %}
                    <div class="control-group">
                        <label class="control-label"></label>
                        <div class="controls">
                            Are you sure you want to remove project named: <strong>{{ employee.username }}</strong>?
                        </div>
                    </div>
              <div class="form-actions">
                  <button type="submit" value="Confirm" class="btn btn-danger">Yes</button>
              <button type="button" value="Cancel" class="btn btn-light"><a href="{% url 'allocationlistforlead' %}">No</a></button>
              </div>
              {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
              {% endif %}<br>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/project/allocationlist.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="span6">
        <div class="widget-box">
          <div class="widget-title">
            <h5>Allocated Resources List</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Project Name</th>
                  <th>Employee Username</th>
                  <th>Role</th>
                  <th>Allocation in percentage</th>
                  <th>Update/Delete</th>
                </tr>
              </thead>
              <tbody>
              {% for t in projectallocation_list %}
                <tr>
                  <td class="taskDesc">{{ t.project.name }}</td>
                  <td class="taskDesc">{{ t.user.username }}</td>
                  <td class="taskDesc">{{ t.get_role_display }}</td>
                  <td class="taskDesc">{{ t.allocation }}</td>
                  <td class="taskOptions"><a href="{% url 'allocationupdate' t.id %}" class="tip-top" data-original-title="Update"><i class="icon-pencil"></i></a>
                      <a href="{% url 'allocationdelete' t.user.id t.allocation %}" class="tip-top" data-original-title="Delete"><i class="icon-remove"></i></a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
  {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <div class="pagination dataTables_paginate fg-buttonset ui-buttonset fg-buttonset-multi ui-buttonset-multi paging_full_numbers">
            {% if page_obj.has_previous %}
                <a class="previous fg-button ui-button ui-state-default page-link ui-state-disabled" href="?page={{ page_obj.previous_page_number }}"><strong>&laquo;</strong></a>
            {% else %}
              <a class="previous fg-button ui-button ui-state-default page-link ui-state-default"><span>&laquo;</span></a>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <a class="page-item active page-link fg-button ui-button ui-state-disabled" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
              {% else %}
                <a class="page-link fg-button ui-button ui-state-default" href="?page={{ i }}">{{ i }}</a>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}" class="page-item page-link page-link fg-button ui-button ui-state-disabled">&raquo;</a>
            {% else %}
              <a class="page-link fg-button ui-button ui-state-default ui-state-default"><span>&raquo;</span></a>
            {% endif %}
          </div>
        </nav>
    {% endif %}
</div>
{% endblock %}

templates/project/allocationlistforlead.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="span6">
        <div class="widget-box">
          <div class="widget-title">
            <h5>Allocated Resources List</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Project Name</th>
                  <th>Employee Username</th>
                  <th>Role</th>
                  <th>Allocation in percentage</th>
                  <th>Update/Delete</th>
                </tr>
              </thead>
              <tbody>
              {% for t in projectallocation_list %}
                <tr>
                  <td class="taskDesc">{{ t.project.name }}</td>
                  <td class="taskDesc">{{ t.user.username }}</td>
                  <td class="taskDesc">{{ t.get_role_display }}</td>
                  <td class="taskDesc">{{ t.allocation }}</td>
                  <td class="taskOptions"><a href="{% url 'allocationupdateforlead' t.id %}" class="tip-top" data-original-title="Update"><i class="icon-pencil"></i></a>
                      <a href="{% url 'allocationdeleteforlead' t.user.id t.allocation %}" class="tip-top" data-original-title="Delete"><i class="icon-remove"></i></a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
</div>
{% endblock %}

templates/project/allocationupdate.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="row-fluid">
    <div class="span6">
      <div class="widget-box">
        <div class="widget-title">
          <h5>Resource Information Updating Form</h5>
        </div>
        <div class="widget-content nopadding">
          <form method="post" class="form-horizontal">
           {% csrf_token %}
              {% for field in form %}
            <div class="control-group">
              <label class="control-label">{{ field.label_tag }}</label>
              <div class="controls">
                {{ field }}
                {{ field.errors }}
              </div>
            </div>
              {% endfor %}
              {{ error }}
              <div class="form-actions">
              <button type="submit" value="Update" class="btn btn-success">Update Allocation</button>
              </div>
              {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
              {% endif %}<br>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/project/allocationupdateforlead.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="row-fluid">
    <div class="span6">
      <div class="widget-box">
        <div class="widget-title">
          <h5>Resource Information Updating Form</h5>
        </div>
        <div class="widget-content nopadding">
          <form method="post" class="form-horizontal">
           {% csrf_token %}
              {% for field in form %}
            <div class="control-group">
              <label class="control-label">{{ field.label_tag }}</label>
              <div class="controls">
                {{ field }}
                {{ field.errors }}
              </div>
            </div>
              {% endfor %}
              <div class="form-actions">
              <button type="submit" value="Update" class="btn btn-success">Update Allocation</button>
              </div>
              {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
              {% endif %}<br>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/project/leaddelete.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="row-fluid">
    <div class="span6">
      <div class="widget-box">
        <div class="widget-title">
          <h5>Remove Lead</h5>
        </div>
        <div class="widget-content nopadding">
          <form method="post" class="form-horizontal">
           {% csrf_token %}
                    <div class="control-group">
                        <label class="control-label"></label>
                        <div class="controls">
                            Are you sure you want to remove lead from project: <strong>{{ object }}</strong>?
                        </div>
                    </div>
              <div class="form-actions">
                <button type="submit" value="Confirm" class="btn btn-danger">Yes</button>
                <button type="button" value="Cancel" class="btn btn-light"><a href="{% url 'leadlist' %}">No</a></button>
              </div>
              {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
              {% endif %}<br>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/project/leadlist.html
{% extends "index.html" %}

{% load crispy_forms_tags %}

{% load i18n %}

{% block content %}
<div class="span6">
        <div class="widget-box">
          <div class="widget-title">
            <h5>Team Leads</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Project Name</th>
                  <th>Team Lead</th>
                  <th>Update/Delete</th>
                </tr>
              </thead>
              <tbody>
              {% for t in teamlead_list %}
                <tr>
                  <td class="taskDesc">{{ t.project.name }}</td>
                  <td class="taskDesc">{{ t.user.username }}</td>
                  <td class="taskOptions"><a href="{% url 'leadupdate' t.id %}" class="tip-top" data-original-title="Update"><i class="icon-pencil"></i></a>
                      <a href="{% url 'leaddelete' t.id %}" class="tip-top" data-original-title="Delete"><i class="icon-remove"></i></a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
</div>
{% endblock %}